# Generated by Django 2.0.5 on 2018-05-24 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentenceStructureOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('tag', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SentenceStructureQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('native', models.CharField(max_length=100)),
                ('translation', models.CharField(max_length=100)),
                ('correctOrder', models.CharField(max_length=20)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Exercise')),
            ],
        ),
        migrations.CreateModel(
            name='WordListQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('native', models.CharField(max_length=100)),
                ('translation', models.CharField(max_length=100)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Exercise')),
            ],
        ),
        migrations.AddField(
            model_name='sentencestructureoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SentenceStructureQuestion'),
        ),
    ]
