# Generated by Django 2.0.5 on 2018-05-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180525_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='subscribers',
            field=models.BigIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
