# Generated by Django 2.0.5 on 2018-05-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180528_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='flag',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
