# Generated by Django 2.0.5 on 2018-06-18 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180617_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lessonType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.LessonType'),
        ),
    ]
