# Generated by Django 2.0.5 on 2018-06-20 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_lesson_lessontype'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonCompleted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=2, max_digits=3)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
    ]
