# Generated by Django 2.0.5 on 2018-05-31 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180531_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='public',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Language'),
        ),
    ]
