# Generated by Django 2.0.5 on 2018-06-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_lessoncompleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessoncompleted',
            name='grade',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
