# Generated by Django 2.0.5 on 2018-06-19 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_lesson_lessontype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentencestructureoption',
            name='question',
        ),
        migrations.RemoveField(
            model_name='sentencestructurequestion',
            name='lesson',
        ),
        migrations.DeleteModel(
            name='SentenceStructureOption',
        ),
        migrations.DeleteModel(
            name='SentenceStructureQuestion',
        ),
    ]
