# Generated by Django 2.0.6 on 2018-06-21 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180620_1403'),
        ('api', '0011_auto_20180619_1101'),
    ]

    operations = [
    ]
