# Generated by Django 2.0.5 on 2018-06-21 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180619_1101'),
        ('api', '0010_auto_20180620_1403'),
    ]

    operations = [
    ]
