# Generated by Django 2.0.5 on 2018-06-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='attempt',
            field=models.IntegerField(default=0),
        ),
    ]
