# Generated by Django 2.0.5 on 2018-06-07 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_favorite'),
        ('api', '0012_auto_20180606_0816'),
    ]

    operations = [
    ]
