# Generated by Django 2.0.5 on 2018-06-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_merge_20180607_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='attempt',
        ),
        migrations.AddField(
            model_name='user',
            name='attempt',
            field=models.IntegerField(default=0),
        ),
    ]
