# Generated by Django 2.0.5 on 2018-06-07 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_merge_20180607_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Course')),
            ],
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='course',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='type',
        ),
        migrations.RemoveField(
            model_name='sentencestructurequestion',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='wordlistquestion',
            name='exercise',
        ),
        migrations.RenameModel(
            old_name='ExerciseType',
            new_name='LessonType',
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.AddField(
            model_name='lesson',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.LessonType'),
        ),
        migrations.AddField(
            model_name='sentencestructurequestion',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Lesson'),
        ),
        migrations.AddField(
            model_name='wordlistquestion',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Lesson'),
        ),
    ]
