# Generated by Django 2.0.5 on 2018-06-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20180607_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='category',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
