# Generated by Django 2.0.5 on 2018-06-08 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20180607_1127'),
        ('api', '0014_auto_20180607_1852'),
    ]

    operations = [
    ]
