# Generated by Django 2.0.5 on 2018-06-07 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20180607_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='type',
        ),
    ]
