# Generated by Django 2.0.5 on 2018-06-08 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20180607_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='type',
        ),
        migrations.AddField(
            model_name='lesson',
            name='native_lang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='native', to='api.Language'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='trans_lang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translation', to='api.Language'),
        ),
    ]
