# Generated by Django 2.0.5 on 2018-06-07 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_lesson_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LessonType',
        ),
    ]
