# Generated by Django 2.0.5 on 2018-06-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_lessontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='grammar',
            field=models.TextField(null=True),
        ),
    ]
