# Generated by Django 2.0.5 on 2018-06-08 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_lesson_grammar'),
        ('api', '0014_auto_20180607_1852'),
    ]

    operations = [
    ]
