# Generated by Django 2.0.5 on 2018-06-08 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_merge_20180608_1250'),
        ('api', '0016_merge_20180608_0759'),
    ]

    operations = [
    ]
